-- MySQL Script generated by MySQL Workbench
-- Sun Oct 15 21:28:04 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gainholder` DEFAULT CHARACTER SET utf8 ;
USE `gainholder` ;

-- -----------------------------------------------------
-- Table `gainholder`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gainholder`.`login` (
  `id_login` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `status` INT(11) NULL,
  PRIMARY KEY (`id_login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gainholder`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gainholder`.`administradores` (
  `id` INT(11) NOT NULL,
  `id_login` INT NULL,
  `nome_completo` VARCHAR(255) NOT NULL,
  `foto_perfil` VARCHAR(255) NULL,
  `status` INT(11) NULL COMMENT '( 1 - P, 2 - B)',
  `tipo` INT NULL DEFAULT 1 COMMENT '( 1 - ADMIN, 2 - Colunista, 3 - Usuário Site)',
  PRIMARY KEY (`id`),
  INDEX `usuario_login_idx` (`id_login` ASC),
  CONSTRAINT `admin_login`
    FOREIGN KEY (`id_login`)
    REFERENCES `gainholder`.`login` (`id_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gainholder`.`colunistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gainholder`.`colunistas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_login` INT NULL,
  `nome_completo` VARCHAR(255) NOT NULL,
  `foto_perfil` VARCHAR(255) NULL,
  `descricao` TEXT NULL,
  `status` INT(11) NULL,
  `tipo` INT NOT NULL DEFAULT 2 COMMENT '( 1 - ADMIN, 2 - Colunista, 3 - Usuário Site)',
  PRIMARY KEY (`id`),
  INDEX `colunista_login_idx` (`id_login` ASC),
  CONSTRAINT `colunista_login`
    FOREIGN KEY (`id_login`)
    REFERENCES `gainholder`.`login` (`id_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gainholder`.`modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gainholder`.`modulos` (
  `id_modulo` INT(11) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `status` INT NULL COMMENT '( 1 L, 2 B )',
  PRIMARY KEY (`id_modulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gainholder`.`permissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gainholder`.`permissoes` (
  `id_permissao` INT NOT NULL AUTO_INCREMENT,
  `id_login` INT NOT NULL,
  `id_modulo` INT NOT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id_permissao`),
  INDEX `permissao_login_idx` (`id_login` ASC),
  INDEX `permissao_pagina_idx` (`id_modulo` ASC),
  CONSTRAINT `permissao_login`
    FOREIGN KEY (`id_login`)
    REFERENCES `gainholder`.`login` (`id_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `permissao_pagina`
    FOREIGN KEY (`id_modulo`)
    REFERENCES `gainholder`.`modulos` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gainholder`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gainholder`.`usuarios` (
  `id_usuario` INT NOT NULL,
  `tipo_legislacao` INT NOT NULL COMMENT '( 1- PF, 2 - PJ)',
  `nome_completo` VARCHAR(255) NOT NULL,
  `cpf` INT(11) NOT NULL,
  `rg` INT(13) NULL,
  `telefone` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL COMMENT '( M, F)',
  `id_login` INT(11) NULL,
  `id_endereco` INT(11) NULL,
  `tipo` INT NULL COMMENT '( 1 - ADMIN, 2 - Colunista, 3 - Usuário site )',
  PRIMARY KEY (`id_usuario`),
  INDEX `usuario_login_idx` (`id_login` ASC),
  CONSTRAINT `usuario_login`
    FOREIGN KEY (`id_login`)
    REFERENCES `gainholder`.`login` (`id_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gainholder`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gainholder`.`categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gainholder`.`conteudos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gainholder`.`conteudos` (
  `id_conteudo` INT NOT NULL AUTO_INCREMENT,
  `id_categoria` INT(11) NOT NULL,
  `banner` VARCHAR(255) NULL,
  `titulo` VARCHAR(255) NULL,
  `texto` TEXT NULL,
  `data_publicacao` DATE NULL,
  `status` INT NULL,
  `tipo` VARCHAR(45) NULL COMMENT '1 - Conteúdo/2 - Artigo',
  `id_autor` INT(11) NULL,
  `nivel` INT(11) NULL,
  PRIMARY KEY (`id_conteudo`),
  INDEX `conteudos_categorias_idx` (`id_categoria` ASC),
  INDEX `conteudos_autores_idx` (`id_autor` ASC),
  CONSTRAINT `conteudos_categorias`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `gainholder`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `conteudos_autores`
    FOREIGN KEY (`id_autor`)
    REFERENCES `gainholder`.`colunistas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gainholder`.`solucoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gainholder`.`solucoes` (
  `id_solucao` INT NOT NULL AUTO_INCREMENT,
  `banner` VARCHAR(255) NOT NULL,
  `banner_titulo` VARCHAR(255) NOT NULL,
  `banner_descricao` TEXT NULL,
  ` titulo` VARCHAR(255) NULL,
  `texto` TEXT NULL,
  `status` INT NULL,
  `tipo` INT NULL,
  `nivel` INT NULL,
  `id_categoria` INT(11) NOT NULL,
  PRIMARY KEY (`id_solucao`),
  INDEX `solucoes_categorias_idx` (`id_categoria` ASC),
  CONSTRAINT `solucoes_categorias`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `gainholder`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gainholder`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gainholder`.`tags` (
  `id_tag` INT NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_tag`, `tag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gainholder`.`tags_conteudos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gainholder`.`tags_conteudos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_tag` INT(11) NOT NULL,
  `id_conteudo` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `tags_tag_idx` (`id_tag` ASC),
  INDEX `tags_conteudo_idx` (`id_conteudo` ASC),
  CONSTRAINT `tags_tag`
    FOREIGN KEY (`id_tag`)
    REFERENCES `gainholder`.`tags` (`id_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tags_conteudo`
    FOREIGN KEY (`id_conteudo`)
    REFERENCES `gainholder`.`conteudos` (`id_conteudo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
